language: node_js
os:
  - linux
node_js:
  - '12'
  - 'stable'
dist: trusty
addons:
  apt:
    packages:
      - g++
      - make
      - libfontconfig1
      - libxrender1
cache:
  directories:
    - node_modules
before_script:
  - chown -R sow /usr/lib/
  #- npm install nyc@latest --save-dev
  #- npm install mocha@latest --save-dev
  #- apt install make
  #- apt install g++
  #- apt install libfontconfig1 libxrender1
install:
  - "npm install"
script:
  # Run test script
  - node test
git:
  depth: 1