language: cpp
os:
  - linux
env:
  matrix:
    - NODE_VERSION="12"
before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
dist: trusty
addons:
  apt:
    packages:
      - g++
      - make
      - libfontconfig1
      - libxrender1
cache:
  directories:
    - node_modules
before_script:
  - if [ $(uname -s) == 'Linux' ]; then sudo apt-get update; fi;
  - if [ $(uname -s) == 'Linux' ]; then sudo apt install make; fi;
  - if [ $(uname -s) == 'Linux' ]; then sudo apt install g++; fi;
  - if [ $(uname -s) == 'Linux' ]; then sudo apt install libfontconfig1 libxrender1; fi;
install:
  - "npm install"
script:
  - sudo chown -R travis /usr/lib/
  # Run test script
  - node test
git:
  depth: 1