language: node_js
os:
  - linux
node_js:
  - '12'
  - 'stable'
dist: trusty
addons:
  apt:
    packages:
      - g++
      - make
      - libfontconfig1
      - libxrender1
cache:
  directories:
    - node_modules
before_script:
  - echo "$USER"
  - sudo apt-get update
  - sudo chown -R $USER /usr/lib/
  - sudo apt install make
  - sudo apt install g++
  - sudo apt install libfontconfig1 libxrender1
install:
  - "npm install"
script:
  # Run test script
  - node test
git:
  depth: 1